version: '3'
services:
  app:
    build: ./docker/app
    image: yii2-app
    container_name: yii2-app
    restart: 'no'
    ports:
      - '8000:80'
    volumes:
      - './:/var/www'
      - './docker/php/php.ini:/etc/php/7.4/apache2/php.ini'
      - './docker/php/php.ini:/etc/php/7.4/cli/php.ini'
    links:
      - mysql
  mysql:
    image: 'mysql:5.7'
    restart: 'no'
    command: '--sql_mode=""'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: database
  adminer:
    image: adminer
    restart: 'no'
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - '8001:80'
    volumes:
      - /sessions